// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _simple_lfsr_next_random_bits_HH_
#define _simple_lfsr_next_random_bits_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct simple_lfsr_next_random_bits : public sc_module {
    // Port declarations 7
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<32> > ap_return;


    // Module declarations
    simple_lfsr_next_random_bits(sc_module_name name);
    SC_HAS_PROCESS(simple_lfsr_next_random_bits);

    ~simple_lfsr_next_random_bits();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<1> > ap_CS_fsm;
    sc_signal< sc_lv<1> > ap_CS_fsm_state1;
    sc_signal< sc_lv<32> > r;
    sc_signal< sc_lv<32> > tmp_9_7_i_fu_454_p10;
    sc_signal< sc_lv<1> > tmp_1_fu_58_p3;
    sc_signal< sc_lv<1> > tmp_2_fu_66_p3;
    sc_signal< sc_lv<1> > tmp_fu_50_p3;
    sc_signal< sc_lv<1> > tmp_3_fu_74_p3;
    sc_signal< sc_lv<1> > tmp2_fu_88_p2;
    sc_signal< sc_lv<1> > tmp1_fu_82_p2;
    sc_signal< sc_lv<1> > tmp_6_fu_112_p3;
    sc_signal< sc_lv<1> > tmp_7_fu_120_p3;
    sc_signal< sc_lv<1> > tmp_5_fu_104_p3;
    sc_signal< sc_lv<1> > tmp_8_fu_128_p3;
    sc_signal< sc_lv<1> > tmp5_fu_142_p2;
    sc_signal< sc_lv<1> > tmp4_fu_136_p2;
    sc_signal< sc_lv<1> > tmp_10_fu_162_p3;
    sc_signal< sc_lv<1> > tmp_11_fu_170_p3;
    sc_signal< sc_lv<1> > tmp_9_fu_154_p3;
    sc_signal< sc_lv<1> > tmp_12_fu_178_p3;
    sc_signal< sc_lv<1> > tmp8_fu_192_p2;
    sc_signal< sc_lv<1> > tmp7_fu_186_p2;
    sc_signal< sc_lv<1> > tmp_14_fu_212_p3;
    sc_signal< sc_lv<1> > tmp_15_fu_220_p3;
    sc_signal< sc_lv<1> > tmp_13_fu_204_p3;
    sc_signal< sc_lv<1> > tmp_16_fu_228_p3;
    sc_signal< sc_lv<1> > tmp3_fu_242_p2;
    sc_signal< sc_lv<1> > tmp9_fu_236_p2;
    sc_signal< sc_lv<1> > tmp_18_fu_262_p3;
    sc_signal< sc_lv<1> > tmp_19_fu_270_p3;
    sc_signal< sc_lv<1> > tmp_17_fu_254_p3;
    sc_signal< sc_lv<1> > tmp_20_fu_278_p3;
    sc_signal< sc_lv<1> > tmp10_fu_292_p2;
    sc_signal< sc_lv<1> > tmp6_fu_286_p2;
    sc_signal< sc_lv<1> > tmp_22_fu_312_p3;
    sc_signal< sc_lv<1> > tmp_23_fu_320_p3;
    sc_signal< sc_lv<1> > tmp_21_fu_304_p3;
    sc_signal< sc_lv<1> > tmp_24_fu_328_p3;
    sc_signal< sc_lv<1> > tmp12_fu_342_p2;
    sc_signal< sc_lv<1> > tmp11_fu_336_p2;
    sc_signal< sc_lv<1> > tmp_26_fu_362_p3;
    sc_signal< sc_lv<1> > tmp_27_fu_370_p3;
    sc_signal< sc_lv<1> > tmp_25_fu_354_p3;
    sc_signal< sc_lv<1> > tmp_28_fu_378_p3;
    sc_signal< sc_lv<1> > tmp14_fu_392_p2;
    sc_signal< sc_lv<1> > tmp13_fu_386_p2;
    sc_signal< sc_lv<1> > tmp_29_fu_404_p3;
    sc_signal< sc_lv<1> > tmp_30_fu_412_p3;
    sc_signal< sc_lv<1> > tmp_31_fu_420_p3;
    sc_signal< sc_lv<1> > tmp_32_fu_428_p3;
    sc_signal< sc_lv<1> > tmp16_fu_442_p2;
    sc_signal< sc_lv<1> > tmp15_fu_436_p2;
    sc_signal< sc_lv<24> > tmp_4_fu_100_p1;
    sc_signal< sc_lv<1> > new_random_bit_i_fu_94_p2;
    sc_signal< sc_lv<1> > new_random_bit_1_i_fu_148_p2;
    sc_signal< sc_lv<1> > new_random_bit_2_i_fu_198_p2;
    sc_signal< sc_lv<1> > new_random_bit_3_i_fu_248_p2;
    sc_signal< sc_lv<1> > new_random_bit_4_i_fu_298_p2;
    sc_signal< sc_lv<1> > new_random_bit_5_i_fu_348_p2;
    sc_signal< sc_lv<1> > new_random_bit_6_i_fu_398_p2;
    sc_signal< sc_lv<1> > new_random_bit_7_i_fu_448_p2;
    sc_signal< sc_lv<8> > tmp_9_7_i_cast_fu_476_p9;
    sc_signal< sc_lv<1> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<1> ap_ST_fsm_state1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<32> ap_const_lv32_1D;
    static const sc_lv<32> ap_const_lv32_19;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<32> ap_const_lv32_1C;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_1B;
    static const sc_lv<32> ap_const_lv32_16;
    static const sc_lv<32> ap_const_lv32_1A;
    static const sc_lv<32> ap_const_lv32_15;
    static const sc_lv<32> ap_const_lv32_14;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<32> ap_const_lv32_11;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_new_random_bit_1_i_fu_148_p2();
    void thread_new_random_bit_2_i_fu_198_p2();
    void thread_new_random_bit_3_i_fu_248_p2();
    void thread_new_random_bit_4_i_fu_298_p2();
    void thread_new_random_bit_5_i_fu_348_p2();
    void thread_new_random_bit_6_i_fu_398_p2();
    void thread_new_random_bit_7_i_fu_448_p2();
    void thread_new_random_bit_i_fu_94_p2();
    void thread_tmp10_fu_292_p2();
    void thread_tmp11_fu_336_p2();
    void thread_tmp12_fu_342_p2();
    void thread_tmp13_fu_386_p2();
    void thread_tmp14_fu_392_p2();
    void thread_tmp15_fu_436_p2();
    void thread_tmp16_fu_442_p2();
    void thread_tmp1_fu_82_p2();
    void thread_tmp2_fu_88_p2();
    void thread_tmp3_fu_242_p2();
    void thread_tmp4_fu_136_p2();
    void thread_tmp5_fu_142_p2();
    void thread_tmp6_fu_286_p2();
    void thread_tmp7_fu_186_p2();
    void thread_tmp8_fu_192_p2();
    void thread_tmp9_fu_236_p2();
    void thread_tmp_10_fu_162_p3();
    void thread_tmp_11_fu_170_p3();
    void thread_tmp_12_fu_178_p3();
    void thread_tmp_13_fu_204_p3();
    void thread_tmp_14_fu_212_p3();
    void thread_tmp_15_fu_220_p3();
    void thread_tmp_16_fu_228_p3();
    void thread_tmp_17_fu_254_p3();
    void thread_tmp_18_fu_262_p3();
    void thread_tmp_19_fu_270_p3();
    void thread_tmp_1_fu_58_p3();
    void thread_tmp_20_fu_278_p3();
    void thread_tmp_21_fu_304_p3();
    void thread_tmp_22_fu_312_p3();
    void thread_tmp_23_fu_320_p3();
    void thread_tmp_24_fu_328_p3();
    void thread_tmp_25_fu_354_p3();
    void thread_tmp_26_fu_362_p3();
    void thread_tmp_27_fu_370_p3();
    void thread_tmp_28_fu_378_p3();
    void thread_tmp_29_fu_404_p3();
    void thread_tmp_2_fu_66_p3();
    void thread_tmp_30_fu_412_p3();
    void thread_tmp_31_fu_420_p3();
    void thread_tmp_32_fu_428_p3();
    void thread_tmp_3_fu_74_p3();
    void thread_tmp_4_fu_100_p1();
    void thread_tmp_5_fu_104_p3();
    void thread_tmp_6_fu_112_p3();
    void thread_tmp_7_fu_120_p3();
    void thread_tmp_8_fu_128_p3();
    void thread_tmp_9_7_i_cast_fu_476_p9();
    void thread_tmp_9_7_i_fu_454_p10();
    void thread_tmp_9_fu_154_p3();
    void thread_tmp_fu_50_p3();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
